### ISSUE TITLE
'MyLogger' object has no attribute 'warning_registry'

### ISSUE THREAD

**Issue by nbmurphy** [sdss/python_template#21]
I’ve encountered the following error a few times in the past. Its reocurrence makes me think there might be a bug in `python_template`. It happens when I use `logger.warning` with a *completely different logger* than the logger `utils/logger.py` included with the template, yet it throws an error in `utils/logger.py`. If I change `logger.warning` to `logger.info` it works as expected with the correct logger.
The offending line is
`self.logger.warning('Encountered unsupported install urls: {}. Skipping...'.format(diff))`
```
sdss_install.utils.logger - ERROR - logger.py - line 172 - Uncaught exception
Traceback (most recent call last):
  File "/Users/ben/Compute/Python/sdss_install/idlutils/bin/sdss_install", line 50, in <module>
    install.install_external_dependencies()
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/install/Install.py", line 303, in install_external_dependencies
    if install_urls: self.install_external_products(install_urls=install_urls)
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/install/Install.py", line 321, in install_external_products
    'Skipping these.')
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/utils/logger.py", line 194, in warning
    if category in self.warning_registry:
AttributeError: 'MyLogger' object has no attribute 'warning_registry'
Traceback (most recent call last):
  File "/Users/ben/Compute/Python/sdss_install/idlutils/bin/sdss_install", line 50, in <module>
    install.install_external_dependencies()
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/install/Install.py", line 303, in install_external_dependencies
    if install_urls: self.install_external_products(install_urls=install_urls)
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/install/Install.py", line 321, in install_external_products
    'Skipping these.')
  File "/Users/ben/Compute/Python/sdss_install/idlutils/python/sdss_install/utils/logger.py", line 194, in warning
    if category in self.warning_registry:
AttributeError: 'MyLogger' object has no attribute 'warning_registry'
[ben@cypher:sdss]$
```

**Comment by albireox** [comment]
I think you may be used an outdated version of the logger from the template. That piece of code has given me serious headaches but I think it's now in a good state. I would suggest you take the code from [logger.py](https://github.com/sdss/python_template/blob/master/{{cookiecutter.repo_name}}/python/{{cookiecutter.package_name|lower}}/utils/logger.py) and copy-paste on top of your existing logger file (depending on what version you're using you may need to change how it's imported and used). The new version of the logger has a much better solution for the warning and you should not get that specific problem.

This reminds me I need to update the documentation for the logger.
